services:

  scraper:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: scraper
    depends_on:
      # - mongodb
      - couchdb
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ./screenshots:/app/screenshots
      - /app/node_modules
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}

  couchdb:
    image: couchdb:3
    container_name: couchdb
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      COUCHDB_USER: ${DB_USER}
      COUCHDB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:

    #   mongodb:
    #     image: mongo:latest
    #     container_name: mongodb
    #     restart: always
    #     ports:
    #       - "27017:27017"
    #     environment:
    #       MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
    #       MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    #     volumes:
    #       - mongo_data:/data/db

    # volumes:
    #   mongo_data:
